### ISSUE TITLE
Deleted the `verdaccio-s3-db.json` in s3 can still request the package list

### ISSUE THREAD

**Issue by yansenlei** [Remitly/verdaccio-s3-storage#24]
I used verdaccio-s3-storage in Docker and I have a problem.

After I release the component, there will be an uploaded package in s3 and the configuration `verdaccio-s3-db.json`. If I delete the `verdaccio-s3-db.json` in s3, I can still find it on the web. List of packages. I am very confused, I did not find the configuration in the Docker container, I see the verdaccio-s3-storage source code ([L116](https://github.com/Remitly/verdaccio-s3-storage/blob/master/src/index.js#L116)) is also directly used s3 `verdaccio-s3-db.json`.

My config.yml:
```yml
store:
  s3-storage:
    bucket: xx-npm-xx
    # keyPrefix: docker-test-prefix
    # region: eu-west-2
    # endpoint: http://localstack-s3:4572
```
